import {MigrationInterface, QueryRunner} from "typeorm";
import {DepartementEntity} from "../src/villes/entity/departement.entity";

export class Migrations1728054292950 implements MigrationInterface {

  public async up(queryRunner: QueryRunner): Promise<void> {
    const clients = [
      {nom: 'BOIS JOLIMONT', departementCode: 972},
      {nom: 'IME LES GOMMIERS', departementCode: 971},
      {nom: 'GCS MANGOT VULCIN', departementCode: 972},
      {nom: 'ASL LA MICHELE 2', departementCode: 972},
      {nom: 'ASL LE GRAND BLEU', departementCode: 972},
      {nom: 'CIRAD', departementCode: 972},
      {nom: 'SC CHAMPIGONE', departementCode: 972},
      {nom: 'ASL DU STADE', departementCode: 972},
      {nom: 'ASL WALL HOUSE', departementCode: 972},
      {nom: 'ASL LIBRE AVENIR', departementCode: 972},
      {nom: 'ASL LES ACACIAS', departementCode: 972},
      {nom: 'ASL BEAUSEJOUR', departementCode: 972},
      {nom: 'GENDARMERIE', departementCode: 972},
      {nom: 'EHPAD LES GLIRICIDIAS', departementCode: 972},
      {nom: 'LE CLOS D\'ISTYA', departementCode: 973},
      {nom: 'ATTILA CABASSOU', departementCode: 973},
      {nom: 'EUREKA', departementCode: 971},
      {nom: 'KARL\'S TRAITEUR', departementCode: 971},
      {nom: 'SDC SALAKA', departementCode: 971},
      {nom: 'VILLE ST ESPRIT', departementCode: 972},
      {nom: 'SDC REPUBLIQUE GALLIENI', departementCode: 972},
      {nom: 'SDC CALANTHE', departementCode: 972},
      {nom: 'ASL PETITE FRANCE', departementCode: 972},
      {nom: 'Résidence VIVENTURA', departementCode: 973},
      {nom: 'RESIDENCE LA RHUMERIE', departementCode: 973},
      {nom: 'PALMA ROSA', departementCode: 973},
      {nom: 'AUPLATA', departementCode: 973},
      {nom: 'TERRA NOVA', departementCode: 973},
      {nom: 'MAHO CIGARE', departementCode: 973},
      {nom: 'SDC LE CLOS DE SAMANA 2', departementCode: 973},
      {nom: 'SDC LA KAMPAGN', departementCode: 973},
      {nom: 'SDC LES ESTUDOMS', departementCode: 973},
      {nom: 'APAJH IME', departementCode: 973},
      {nom: 'SDE RESIDENCE ANGELIQUE', departementCode: 973},
      {nom: 'LYCEE LEON GONTRAN DAMAS', departementCode: 973},
      {nom: 'LYCEE MELKIOR GARRE', departementCode: 973},
      {nom: 'SDC CELINA', departementCode: 973},
      {nom: 'LYCEE LEON GONTRAN DAMAS', departementCode: 973},
      {nom: 'SDC CITRONNELLE', departementCode: 973},
      {nom: 'SDC CORIANDRE', departementCode: 973},
      {nom: 'SDC PITAYA', departementCode: 973},
      {nom: 'ASL PETIT HAVRE', departementCode: 971},
      {nom: 'SDC MIZALO', departementCode: 971},
      {nom: 'SDC DE LA BAIE', departementCode: 971},
      {nom: 'SDC ALIZEA', departementCode: 971},
      {nom: 'PREFECTURE REGION GUADELOUPE', departementCode: 971},
      {nom: 'MAIRIE DE PETIT BOURG', departementCode: 971},
      {nom: 'SDC LES PALETUVIERS', departementCode: 971},
      {nom: 'SDC FRUYAPEN', departementCode: 971},
      {nom: 'SARL MODEL\'AGE', departementCode: 971},
      {nom: 'SCI PETIT BOURG CANNELLE', departementCode: 972},
      {nom: 'SCI BG MONTAIGNE', departementCode: 972},
      {nom: 'SDC LES PLUVIERS', departementCode: 972},
      {nom: 'SDC LES JARDINS DE SUZINI', departementCode: 973},
      {nom: 'SDC TERRASSE DE MONTABO', departementCode: 973},
      {nom: 'SDC VIOLA', departementCode: 973},
      {nom: 'SDC LE CLOS DES ALPINIAS', departementCode: 973},
      {nom: 'SDC PAPAYER', departementCode: 971},
      {nom: 'CENTRE HOSPITALIER LOUIS-DANIEL BEAUPERTHUY', departementCode: 971},
      {nom: 'SDC SEMAG', departementCode: 971},
      {nom: 'MAJESTIC', departementCode: 971},
      {nom: 'IME IONA', departementCode: 971},
      {nom: 'CHUM', departementCode: 972},
      {nom: 'SDC BELVEDERE', departementCode: 972},
      {nom: 'ASL ARC EN CIEL', departementCode: 972},
      {nom: 'SDC LA CANONNIERE', departementCode: 972},
      {nom: 'COLLEGE DILLON 2', departementCode: 972},
      {nom: 'SDC ARGANE', departementCode: 972},
      {nom: 'RESIDENCE TERRASSES MARINA', departementCode: 972},
      {nom: 'SDC RESIDENCE SYRIANNE', departementCode: 973},
      {nom: 'AXIONNAZ', departementCode: 973},
      {nom: 'SDC TERRASSE DE MONTABO', departementCode: 973},
      {nom: 'SDC TERRASSES DE BADUEL', departementCode: 973},
      {nom: 'SDC LES MOMBINS 3', departementCode: 973},
      {nom: 'SDC FORUM BADUEL', departementCode: 973},
      {nom: 'SDC ATHELIA', departementCode: 973},
      {nom: 'CCOG (Abattoir de Mana)', departementCode: 973},
      {nom: 'SDC TERRASSES DE BADUEL', departementCode: 973},
      {nom: 'Carine KUO TSING JEN-CRUMIERE', departementCode: 973},
      {nom: 'SEMSAMAR SLM', departementCode: 973},
      {nom: 'SDC FORUM DE BADUEL', departementCode: 973},
      {nom: 'GRAN PARADISIO', departementCode: 973},
      {nom: 'NEVADA', departementCode: 971},
      {nom: 'FOYER DE L\'ESPERANCE', departementCode: 972},
      {nom: 'ASL LES FLIBUSTIERS', departementCode: 972},
      {nom: 'TOUR GERMAINE', departementCode: 972},
      {nom: 'TOUR GERMAINE', departementCode: 972},
      {nom: 'COLLEGE SUZANNE ROUSSI CESAIRE', departementCode: 972},
      {nom: 'SDC LA MOUINA', departementCode: 972},
      {nom: 'NEVISSE', departementCode: 972},
      {nom: 'SDC UNION TAMARIS', departementCode: 972},
      {nom: 'CLOS POINTE LYNCH', departementCode: 972},
      {nom: 'RESIDENCE FOND CORRE (Bâche)', departementCode: 972},
      {nom: 'RESIDENCE LES MANGUIERS', departementCode: 972},
      {nom: 'RESIDENCE CALDEIRA', departementCode: 972},
      {nom: 'LES TROIS POIRIERS', departementCode: 972},
      {nom: 'SDC COCONUT PLAGE', departementCode: 973},
      {nom: 'SDC SUNRISE - SDC SUNSET', departementCode: 973},
      {nom: 'BATIMENT GUYANAIS', departementCode: 973},
      {nom: 'SDC EDEN ROC', departementCode: 973},
      {nom: 'SDC ATLANTIS', departementCode: 973},
      {nom: 'SDC ANSE MONTABO', departementCode: 973},
      {nom: 'SDC FLEUR DES CARAIBES', departementCode: 971},
      {nom: 'SDC BELLEVUE LES SALINES', departementCode: 971},
      {nom: 'GCBC', departementCode: 971},
      {nom: 'RESIDENCE DU PARC', departementCode: 972},
      {nom: 'ASL LE MONT VERT', departementCode: 972},
      {nom: 'MAIRIE TROIS ILETS', departementCode: 972},
      {nom: 'COMGEND', departementCode: 972},
      {nom: 'SDC PAPRIKAU', departementCode: 972},
      {nom: 'SDC PERLE NOIRE', departementCode: 973},
      {nom: 'SDC BUTERFLY', departementCode: 973},
      {nom: 'SDC NORD BEACH', departementCode: 973},
      {nom: 'GRAND PORT MARITIME', departementCode: 973},
      {nom: 'AGROPARISTECH', departementCode: 973},
      {nom: 'ROUTES DE GUADELOUPE', departementCode: 971},
      {nom: 'ASL DOMAINE DU PARC', departementCode: 971},
      {nom: 'MAS UDAF', departementCode: 971},
      {nom: 'VILLE ST ESPRIT', departementCode: 972},
      {nom: 'SDC VICTORIA', departementCode: 973},
      {nom: 'RESIDENCE ANGELIQUE 2 / SCI COROSSOL 502', departementCode: 973},
      {nom: 'SDC CREOL\'ILES', departementCode: 971},
      {nom: 'CHU  / PZQ SURP', departementCode: 972},
      {nom: 'CHU LA MEYNARD', departementCode: 972},
      {nom: 'CHU LA MEYNARD', departementCode: 972},
      {nom: 'SDC BELLE VUE DU PHARE', departementCode: 971},
      {nom: 'RESIDENCE COMPAS', departementCode: 973},
      {nom: 'SDC CHRYSTAL BEACH', departementCode: 971},
      {nom: 'SDC DAHLIA', departementCode: 972},
      {nom: 'SDC RESIDENCE MELODY', departementCode: 972},
      {nom: 'CH CAYENNE', departementCode: 973},
      {nom: 'SDC LA BELLE EOLE', departementCode: 971},
      {nom: 'SDC TOPAZE', departementCode: 973},
      {nom: 'RESIDENCE ST PIERRE', departementCode: 972},
      {nom: 'SCI IMUTURF', departementCode: 972},
      {nom: 'GCS MANGOT VULCIN', departementCode: 972},
      {nom: 'SDC MONTRAVEL', departementCode: 973},
      {nom: 'SCCV PRIMEROSE', departementCode: 972},
      {nom: 'LOT N°1 -CENTRE NORD', departementCode: 972},
      {nom: 'LOT 3', departementCode: 972},
      {nom: 'SDC LES JARDINS DE PLAISANCE', departementCode: 971},
      {nom: 'RESIDENCE VENT LEVE', departementCode: 972},
      {nom: 'RESIDENCE DANMIE', departementCode: 972},
      {nom: 'TESIDENCE DE LA BAIE BAT 1', departementCode: 972},
      {nom: 'TESIDENCE DE LA BAIE BAT 2', departementCode: 972},
      {nom: 'RESIDENCE CARRIERE DOREE', departementCode: 972},
      {nom: 'RESIDENCE SENPIL', departementCode: 972},
      {nom: 'RESIDENCE KABEL ET BELE', departementCode: 972},
      {nom: 'RESIDENCE KOALINE', departementCode: 973},
      {nom: 'RESIDENCE ACAJOU', departementCode: 972},
      {nom: 'RESIDENCE CASSIS', departementCode: 973},
      {nom: 'SDC JARDIN DE TAMARIS', departementCode: 973},
      {nom: 'COLLEGE IV', departementCode: 973},
      {nom: 'SDC SAINT CYR', departementCode: 973},
      {nom: 'SDC DIAMANT', departementCode: 973},
      {nom: 'VOLTALIA', departementCode: 973},
      {nom: 'SDC CITY MARKET KWATA', departementCode: 973},
      {nom: 'SDC PANAMA', departementCode: 971},
      {nom: 'SDC QUISSY', departementCode: 972},
      {nom: 'SDC LES FLAMBOYANTS', departementCode: 971},
    ];

    for (let client of clients) {
      const departmentEntity = await queryRunner.manager.findOneBy(
        DepartementEntity,
        {
          code: `${client.departementCode}`,
        },
      );

      await queryRunner.manager.save('clients', {
        nom: client.nom.trim(),
        departementId: departmentEntity.id,
      });
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
  }

}
